### PR TITLE
Add homepage test case

### PR DESCRIPTION
**Pull request by hrithik-shah**
Added test cases for homepage, login, signup, and logout.

### CODE REVIEW

**Comment by hrithik-shah** [comment]
Added the success view, which was giving us a bug

**Review by Nikita-B05 — APPROVED** [review]
Test cases and bug fixes are valid

**Review by marinatedshrimp — APPROVED** [review]
looks good, adds necessary changes and doesnt break code.

**Review by abhi-praj — APPROVED** [review]
I approve this pull request, it adds the homepage test case and fixes a critical bug in Main.java.

**Pull request merged**
