### PR TITLE
Decision log view, interface adapter, test, and game over view

### PR DESCRIPTION
**Pull request by marinatedshrimp**
dont mind if the database looks changed, it didnt come up when i pulled from main so i copy pasted it to my branch but the content should be the same.

### CODE REVIEW

**Comment by hrithik-shah** [comment]
Switching to decision log view is not working. Please fix and make a new pull request.

**Review by Nikita-B05 — COMMENTED** [review]
Decision log is not linked to the homepageview

**Review by hrithik-shah — CHANGES_REQUESTED** [review]
Switching to decision log view is not working. Please fix and make a new pull request.

**Review by Nikita-B05 — CHANGES_REQUESTED** [review]
The Decision log is not accessible from the homepageview

**Review by Nikita-B05 — CHANGES_REQUESTED** [review]
Don't push .idea. Please remove.

**Review by hrithik-shah — CHANGES_REQUESTED** [review]
There is a breaking bug, preventing the code from compiling.

**Pull request closed without merging**
